apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: garden-api
  template:
    metadata:
      labels:
        app: garden-api
    spec:
      containers:
        - name: garden-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: 5000
