apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: garden-web
  template:
    metadata:
      labels:
        app: garden-web
    spec:
      containers:
        - name: garden-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          ports:
            - containerPort: 8080
