api:
  image:
    repository: ""
    tag: ""
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000

web:
  image:
    repository: ""
    tag: ""
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
